name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Add steps to install and configure the ODBC driver
    - name: Install SQL Server Native Client 11.0 ODBC Driver
      run: |
          sudo apt update
          sudo apt install unixodbc unixodbc-dev
    - name: Configure ODBC Driver
      run: |
        echo "[ODBC Driver 17 for SQL Server]
        Description=Microsoft ODBC Driver 17 for SQL Server
        Driver=/path/to/odbc/driver/libmsodbcsql-17.8.so.1" | sudo tee -a /etc/odbcinst.ini

    - name: Set Environment Variables
      run: |
        export ODBCINI=/path/to/odbc.ini
        export ODBCSYSINI=/path/to/odbcinst.ini

    # Now run your tests
    - name: Run tests
      run: |
        pytest tests/
